server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/creative_ideas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: your_password_here
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update         # `validate` or `none` in production, `update` for dev
    show-sql: true             # false in production
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/creative_ideas
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200

  elasticsearch:
    host: localhost

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
